import type { Metadata } from 'next'
import '../globals.css'
import Link from 'next/link'


import {getPages} from '@/sanity/sanity-utils'


export const metadata: Metadata = {
  title: ' Marvel Portfolio',
  description: 'Generated by Next + Sanity',
}

export default  async  function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pages  = await getPages();
  return (
    <html lang="en">
      <body className='max-w-6xl mx-auto p-10' >
        <header className='flex justify-between align-middle text-center items-center' >
         <h1 className='text-3xl font-bold'>
         <Link  href="/" className='bg-gradient-to-r from-green-400 to-blue-600 bg-clip-text text-transparent'>
          Marvel
          </Link>
          </h1>

          <div className='flex gap-2'>
            {pages.map((page) =>(
              <Link key={page._id}
              href={`/${page.slug}`} className='text-sm hover:text-blue-500' >
              {page.title}
              </Link>
            ))}
          </div>

        </header>
        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
